### ISSUE TITLE
Full LLE emulation

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/OpenXBOX#16]
Due to the excessive complexity in implementing and maintaining the high-level kernel implementation, I'm making a shift in focus to full LLE, as seen in the `full-lle` branch. The current kernel work will be put on hold until a better solution is found.

I know this goes against the original goal of the project, but the added complexity of the full kernel implementation is not worth the trouble of facilitating usage of the emulator, especially considering that Xbox hardware emulation is still incipient. Besides, there are many other successful emulators out there that don't work without a BIOS file (such as PCSX2), and it's relatively easy to extract the necessary files from an Xbox machine.

**Comment by 0DaveX** [comment]
imo **full LLE** is the way to go, too.
however I don't agree with:
>  it's relatively easy to extract the necessary files 

regarding the MCPX rom (and kernel with Init section on softmodded xboxes)

**Comment by StrikerX3** [comment]
I agree. I don't know what I was thinking when I wrote that. I meant to say it's not impossible.

**Comment by StrikerX3** [comment]
The emulator now has a workable infrastructure for LLE-ing hardware devices.
