### ISSUE TITLE
Parse command line arguments

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/OpenXBOX#18]
The command line front-end should be able to parse command line arguments.

https://github.com/skeeto/optparse seems like a good portable library to help with this.

**Comment by lpmusicon** [comment]
Hi, @StrikerX3 Anything against using [boost - program options](https://www.boost.org/doc/libs/1_67_0/doc/html/program_options.html) to achieve this? I could write Pull request using it or optparse you provided.

**Comment by StrikerX3** [comment]
The problem with Boost is that it's a *huge* library; including it just to parse command line arguments is a bit excessive. I'd be up for it if we were going to use several other components of the library, but the code is already using C++14/17 standard library features in place of those.

**Comment by lpmusicon** [comment]
@StrikerX3 Added pull request, feel free to check and ask if I should change anything

**Comment by StrikerX3** [comment]
Implemented on PR #37.
