### ISSUE TITLE
Add support for KVM on Linux

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/OpenXBOX#19]
[KVM](https://www.linux-kvm.org/page/Main_Page) is Linux's virtualization platform, supporting both Intel and AMD hardware-assisted virtualization solutions.

We want to implement this as a Linux-only CPU module.

**Comment by darrena092** [comment]
Pretty much implemented in my kvm branch now. Few additional bits to do then will submit a PR.

**Comment by darrena092** [comment]
Submitted https://github.com/StrikerX3/OpenXBOX/pull/35

**Comment by StrikerX3** [comment]
Merged.
