### ISSUE TITLE
Create a plugin system

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/OpenXBOX#6]
In the remove-glib branch I removed GLib as a dependency on Windows platforms due to the excessive complexity of the library and the fact that we were barely using its features. The only real reason for it to be included was the (incomplete) NV2A renderer which I haven't touched because the kernel barely works and doesn't even reach the `main` function of Microsoft XDK titles anyway, so there is no point in having a renderer yet.

After mulling over the problem, I figured that the emulator would be in a much better shape if it had a modular plugin system where the core provides the basic emulation features, including the custom kernel implementation, and interfaces for plugins to implement Xbox hardware, such as the CPU, NV2A and others. That way, the core can be small, clean and have very few dependencies, while the plugins can provide implementations using whatever compiler and libraries they want, as long as they obey the supplied interfaces.

**Comment by PatrickvL** [comment]
Regarding the renderer - today the Cxbx-Reloaded NV2A renderer (which as you know is a copy of the split-up OpenXbox nv2a rendere) was fixed to bypass a hang (not the last one, unfortunately). Anyway, locks and condition variables are now done using `std::mutex`, `std::unique_lock` and `std::condition_variable`, which helps portability.

**Comment by StrikerX3** [comment]
Commit 8578e5c implements the plugin system for CPUs and turns the Unicorn implementation into a dynamically loaded plugin for the emulator. Files were also moved into an openxbox subfolder within the source folder so that includes look like `#include "openxbox/..."`, avoiding possible file name clashes.
